export const LOAD_TOURS_SUCCESS = "LOAD_TOURS_SUCCESS";
export const CREATE_TOUR_SUCCESS = "CREATE_TOUR_SUCCESS";
export const UPDATE_TOUR_SUCCESS = "UPDATE_TOUR_SUCCESS";

export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";

export const LOAD_FOTOS_SUCCESS = "LOAD_FOTOS_SUCCESS";
