export const CREATE_COURSE = "CREATE_COURSE";
export const CREATE_TOUR = "CREATE_TOUR";
export const LOAD_TOURS_SUCCESS = "LOAD_TOURS_SUCCESS";
export const LOAD_FOTOS_SUCCESS = "LOAD_FOTOS_SUCCESS";
